"""Functional signed INT8 4x4 matrix multiplication, with integer results."""


def _validate_matrix(matrix, name):
    """Require four rows of four Python integers in the signed INT8 range."""
    if not isinstance(matrix, (list, tuple)) or len(matrix) != 4:
        raise ValueError(f"{name} must contain exactly four rows")
    for i, row in enumerate(matrix):
        if not isinstance(row, (list, tuple)) or len(row) != 4:
            raise ValueError(f"{name}[{i}] must contain exactly four elements")
        for j, value in enumerate(row):
            # bool is a subclass of int, but is not an INT8 matrix operand.
            if type(value) is not int:
                raise TypeError(f"{name}[{i}][{j}] must be a Python integer")
            if not -128 <= value <= 127:
                raise ValueError(
                    f"{name}[{i}][{j}]={value} is outside signed INT8 [-128, 127]"
                )


def matmul_4x4(A, B):
    """Return A times B, validating signed INT8 inputs without modifying them.

    Accept lists or tuples of four rows. Accumulation uses unbounded Python
    integers; outputs are not clipped or wrapped to INT8.
    """
    _validate_matrix(A, "A")
    _validate_matrix(B, "B")
    return [
        [sum(A[i][k] * B[k][j] for k in range(4)) for j in range(4)]
        for i in range(4)
    ]


def _print_matrix(name, matrix):
    width = max(len(str(value)) for row in matrix for value in row)
    print(f"{name} =")
    for row in matrix:
        print("  [" + " ".join(f"{value:>{width}}" for value in row) + "]")


def _run_case(name, A, B, expected):
    C = matmul_4x4(A, B)
    print(name)
    for label, matrix in (("A", A), ("B", B), ("C", C)):
        _print_matrix(label, matrix)
    if C != expected:
        raise AssertionError(f"{name}: expected {expected}, got {C}")
    print(f"PASS: {name}\n")


def main():
    A = [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12],
        [13, 14, 15, 16],
    ]
    identity = [
        [1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1],
    ]
    _run_case("Test 1: A times identity", A, identity, A)

    signed_A = [
        [-3, 0, 5, -2],
        [7, -4, 1, 0],
        [-128, 6, -7, 3],
        [2, -1, 0, 127],
    ]
    signed_B = [
        [4, -2, 0, 7],
        [-5, 3, 6, 0],
        [1, 0, -4, 2],
        [0, 8, -3, -6],
    ]
    # Independently calculated constants, not generated by matmul_4x4.
    signed_expected = [
        [-7, -10, -14, 1],
        [49, -26, -28, 51],
        [-549, 298, 55, -928],
        [13, 1009, -387, -748],
    ]
    _run_case("Test 2: signed values and INT8 extremes", signed_A, signed_B,
              signed_expected)
    print("PASS: all golden model sanity tests")


if __name__ == "__main__":
    main()
